### ISSUE TITLE
Ability to change domainame

### ISSUE THREAD

**Issue by hansmorb** [robertdebock/ansible-role-roundcubemail#4]
I am sorry if this is a stupid question but I would like to have my Roundcube accessible at webmail.example.com and not under example.com directly, how would I accomplish that?

**Comment by robertdebock** [comment]
You can configure Apache httpd using the [`httpd`](https://galaxy.ansible.com/robertdebock/httpd) role. Something like this:

```yaml
  roles:
    - role: robertdebock.httpd
      httpd_vhosts:
        - name: roundcubemail
          servername: webmail.example.com
          documentroot: /var/www/html/roundcubemail
```

I'll write an example in [`molecule/default/converge.yml`](https://github.com/robertdebock/ansible-role-roundcubemail/blob/master/molecule/default/converge.yml) so it's documented and tested. Give me some time for that please.

Regards,

Robert.
